In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
data = pd.read_csv("data/simple_linear_data.csv")

In [17]:
data.insert(0,"b",1)

In [18]:
data.head()

b  G2  G3
0  1  30  30
1  1  25  30
2  1  40  50
3  1  70  75
4  1  50  50

In [20]:
X = data.drop(['G3'],axis = 1).values
y = data.G3.values

In [21]:
print(X)

[[ 1 30]
 [ 1 25]
 [ 1 40]
 [ 1 70]
 [ 1 50]
 [ 1 75]
 [ 1 60]
 [ 1 25]
 [ 1 90]
 [ 1 75]
 [ 1 40]
 [ 1 60]
 [ 1 70]
 [ 1 50]
 [ 1 80]
 [ 1 70]
 [ 1 70]
 [ 1 50]
 [ 1 25]
 [ 1 50]
 [ 1 70]
 [ 1 75]
 [ 1 75]
 [ 1 65]
 [ 1 45]
 [ 1 45]
 [ 1 60]
 [ 1 80]
 [ 1 55]
 [ 1 60]
 [ 1 55]
 [ 1 80]
 [ 1 80]
 [ 1 50]
 [ 1 70]
 [ 1 35]
 [ 1 80]
 [ 1 80]
 [ 1 60]
 [ 1 65]
 [ 1 50]
 [ 1 60]
 [ 1 90]
 [ 1 40]
 [ 1 50]
 [ 1 40]
 [ 1 60]
 [ 1 95]
 [ 1 75]
 [ 1 35]
 [ 1 65]
 [ 1 65]
 [ 1 55]
 [ 1 50]
 [ 1 65]
 [ 1 45]
 [ 1 75]
 [ 1 75]
 [ 1 50]
 [ 1 80]
 [ 1 55]
 [ 1 40]
 [ 1 50]
 [ 1 45]
 [ 1 50]
 [ 1 75]
 [ 1 65]
 [ 1 35]
 [ 1 45]
 [ 1 80]
 [ 1 75]
 [ 1 50]
 [ 1 30]
 [ 1 60]
 [ 1 60]
 [ 1 45]
 [ 1 55]
 [ 1 55]
 [ 1 40]
 [ 1 25]
 [ 1 60]
 [ 1 50]
 [ 1 30]
 [ 1 75]
 [ 1 50]
 [ 1 45]
 [ 1 35]
 [ 1 70]
 [ 1 50]
 [ 1 30]
 [ 1 35]
 [ 1 85]
 [ 1 30]
 [ 1 50]
 [ 1 65]
 [ 1 50]
 [ 1 75]
 [ 1 45]
 [ 1 70]
 [ 1 45]
 [ 1 35]
 [ 1 85]
 [ 1 65]
 [ 1 30]
 [ 1 90]
 [ 1 55]
 [ 1 40]
 [ 1 90]
 [ 1 65]
 [ 1 75]
 [ 1 95]
 

In [23]:
X.shape

(395, 2)

In [33]:
def predict(X,weights):
    return np.dot(X,weights)    

In [12]:
def error(y_pred,y_actual):
    mse = (1/2*y_actual[0].shape) * np.sum((y_pred-y_actual)**2)
    return mse

In [13]:
def gradient(X,y_true,y_pred):
    gradient = []
    
    gradient[0][0] = (1/X[0].shape) * np.sum(np.dot(X[:,0],(y_pred-y_true)))
    gradient[0][1] = (1/X[1].shape) * np.sum(np.dot(X[:,0],(y_pred-y_true)))
    
    return gradient
    

In [31]:
def compiling(X,y,learning_rate = 0.0001, iterations = 1000):
    
    weights = np.random.randn((2,1))   
    losses = []
    
    y_true = y.reshape(-1,-1)
    
    for i in range(iterations):
        y_pred = predict(X,weights)
        
        mse = error(y_true,y_pred) 
        
        losses.append(mse)
        
        gradient = gradient(X,y_pred,y_true)
        
        weights[0][0] = weights[0][0] - learning_rate*gradient[0][0]
        weights[1][0] = weights[1][0] - learning_rate*gradient[1][0]
        
        
        
        
        
    return weights,losses

[[0.4159802 ]
 [0.56372173]]


In [30]:
y = data.G3.values
y_true = y.reshape(-1,1)
print(y_true)

[[ 30]
 [ 30]
 [ 50]
 [ 75]
 [ 50]
 [ 75]
 [ 55]
 [ 30]
 [ 95]
 [ 75]
 [ 45]
 [ 60]
 [ 70]
 [ 55]
 [ 80]
 [ 70]
 [ 70]
 [ 50]
 [ 25]
 [ 50]
 [ 75]
 [ 75]
 [ 80]
 [ 60]
 [ 40]
 [ 40]
 [ 55]
 [ 75]
 [ 55]
 [ 55]
 [ 60]
 [ 85]
 [ 80]
 [ 60]
 [ 75]
 [ 30]
 [ 90]
 [ 75]
 [ 55]
 [ 65]
 [ 55]
 [ 60]
 [ 90]
 [ 55]
 [ 45]
 [ 30]
 [ 55]
 [100]
 [ 70]
 [ 35]
 [ 65]
 [ 65]
 [ 50]
 [ 55]
 [ 65]
 [ 50]
 [ 75]
 [ 75]
 [ 45]
 [ 80]
 [ 55]
 [ 55]
 [ 45]
 [ 45]
 [ 50]
 [ 75]
 [ 60]
 [ 30]
 [ 40]
 [ 80]
 [ 75]
 [ 50]
 [ 25]
 [ 70]
 [ 55]
 [ 50]
 [ 50]
 [ 55]
 [ 50]
 [ 25]
 [ 60]
 [ 55]
 [ 30]
 [ 75]
 [ 50]
 [ 40]
 [ 30]
 [ 70]
 [ 50]
 [ 35]
 [ 40]
 [ 90]
 [ 30]
 [ 50]
 [ 70]
 [ 50]
 [ 75]
 [ 50]
 [ 70]
 [ 40]
 [ 25]
 [ 85]
 [ 70]
 [ 30]
 [ 90]
 [ 55]
 [ 40]
 [ 90]
 [ 65]
 [ 80]
 [ 95]
 [ 50]
 [ 65]
 [ 95]
 [ 45]
 [ 80]
 [ 70]
 [ 65]
 [ 40]
 [ 65]
 [ 75]
 [ 75]
 [ 65]
 [ 65]
 [ 40]
 [ 60]
 [ 55]
 [ 45]
 [  0]
 [ 90]
 [  0]
 [  0]
 [ 60]
 [ 55]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 60]
 [ 75]
 [  0]
 [ 45]
 [ 55]

In [34]:
def preict(X,weights):
    pred = np.dot(X,weights)
    return pred
    
    
def loss(y_true,y_pred):
    mse = 1/(y_true[0].shape) * np.sum((y_true - y_pred))**2
    return mse
    

def gradient(X,y_true,y_pred):
    
    gradient = []
    
    grad[0][0] = (1/X[0].shape) * np.sum(np.dot(X[:,0],(y_pred-y_true)))
    grad[0][1] = (1/X[0].shape) * np.sum(np.dot(X[:,1],(y_pred-y_true)))
    
    return gradient



In [36]:
X = data.drop(["G3"],axis=1)
y_true = np.reshape(-1,1)

weights = np.random.randn((2,1))
y_pred= predict(X,weights)

gradient = gradient(X,y_pred,y_true)

print(gradient)

TypeError: 'tuple' object cannot be interpreted as an integer

In [43]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data["column"] = data["column"].apply(le.fit_transform)

KeyError: 'column'

In [44]:
data = pd.get_dummies(data,columns = ["a","b","c"], prefix = ["a","b","c"])

KeyError: "['c', 'a'] not in index"

In [ ]:
data = pd.get_dummies(data,columns = ["","",""], prefix = ["","", ""])

In [45]:
df1 = pd.concat(df1,df2,axis = 1)

NameError: name 'df1' is not defined

2e-07

In [ ]:
class LogisticRegression(self,lr = 0.0001,iterations = 100):
    self.lr = lr
    self.iterations = iterations
    self.likelihoods = []
    
    self.eps = 1e-7
    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
        
    
    def likelihood(self,y_pred,y_true):
        
        y_pred = np.maximum(np.full(y_pred.shape,self,eps) , np.minimum(np.full(y_pred.shape,1-self.eps),y_pred))
        
        loss =  np.mean((y_true*np.log(y_pred) + (1 - y_true)*np.log(1-y_pred)))
    
    def fit(self,X,y):
        num_examples = X[0].shape
        num_features = X[1].shape
        
        self.weights = np.random.rand(num_features)
        
        z = np.dot(X,self.weights)
        
        y_pred = self.predict(z)
        
        loss = likelhood(y_pred,y_true)
        
        
        
    
    
    def predict(self,X):
        pass
    
    def predict(self,X,y,threshold = 0.5):
        pass
    
    

In [49]:
mat = np.random.rand(10,10)
mat.shape
print(mat)

[[0.551882   0.9763302  0.01815805 0.35744798 0.52481285 0.67111657
  0.69379553 0.97478571 0.2324011  0.8978953 ]
 [0.68869709 0.76336859 0.47755343 0.79352702 0.69195113 0.38123307
  0.73501728 0.19422203 0.44121285 0.33781554]
 [0.98191585 0.21978011 0.7261786  0.65111522 0.50566547 0.42713782
  0.63274973 0.72669847 0.28907969 0.34291353]
 [0.79564742 0.22405662 0.63438945 0.11727964 0.35920677 0.45739652
  0.1557857  0.75726297 0.76888837 0.00302846]
 [0.07312968 0.94192976 0.57825699 0.60267057 0.10146517 0.33359173
  0.34191866 0.57838851 0.84727653 0.22427133]
 [0.54352985 0.46416444 0.4231061  0.39138772 0.23964974 0.05840562
  0.98952279 0.97254396 0.6236201  0.64144557]
 [0.61414678 0.38846897 0.52108371 0.51508872 0.65969569 0.59701147
  0.79941622 0.8045317  0.19443379 0.96682754]
 [0.67519718 0.51798201 0.79278512 0.53816547 0.68610193 0.63126451
  0.57355605 0.06272421 0.70851457 0.73513789]
 [0.75712301 0.19486169 0.96890181 0.95466188 0.86476192 0.95624275
  0.8015048 

In [50]:
mat_inv = np.linalg.inv(mat)
mat_inv

array([[ 0.84267256, -0.31894795,  1.96102723, -0.16436629, -0.55197705,
        -0.0561621 , -1.5185903 ,  0.58635816, -0.49643265, -0.05819815],
       [ 1.34994625, -2.042638  ,  1.8011806 , -1.89520556,  0.93188123,
        -0.45540907, -2.19595938,  1.18938554,  0.10729939,  1.07235163],
       [ 0.37686781, -3.89676605,  2.57194249, -2.60130369,  1.2742891 ,
        -0.33217399, -1.95461672,  2.10420913,  0.58379139,  1.48316623],
       [-1.80521582,  3.94528132, -1.06121462,  1.93959942,  0.23715125,
        -0.74723796,  3.75381318, -2.82113879, -1.0738268 , -1.4583072 ],
       [-2.29278158,  3.44364109, -3.15708603,  2.43890802, -0.12123449,
        -1.22454939,  5.18917447, -2.79475871, -0.80298815,  0.0366481 ],
       [ 2.1289811 , -1.85017989,  0.1161493 , -0.77575979, -0.75047582,
         0.78380409, -3.85946642,  2.34304231,  1.72648189, -0.29517774],
       [ 1.77277177, -2.31860177,  0.37997915, -2.19077915, -0.95719017,
         2.31071606, -4.86356739,  2.6794914 

In [ ]:
def newton_opt(X,y,max_iter=100):
    
    weights = np.random.randn(X.shape[1])
    for i in range(max_iter):
        z = np.dot(X,weights)
        y_pred = sigmoid(z)
        
        grad = (1/X.shape[0]) * np.dot(X.T,(y_pred-y_true))
        